using System;

/*  Purpose:    Calculate and display the sales amount by the West Coast unit
 *  
 *  Input:      None
 *  
 *  Process:    Set salesTotal = 5.3Millon
 *              Set salesPercent = 0.43
 *              salesAmount = salesTotal * salesPercent 
 *  
 *  Output:     Sales amount generated by the West Coast unit
 * 
 * */
namespace BasicProgrammingProblem01
{
    class Program
    {
        static void Main(string[] args)
        {
            // Set salesTotal to $5.3M
            double salesTotal = 5300000;
            // Set salesPercent to 0.43
            double salesPercent = 0.43;
            // Calculate salesAmount using formula:
            //      salesAmount = salesTotal * salesPercent
            double salesAmount = salesTotal * salesPercent;
            // Display values for salesTotal, salesPercent, and salesAmount
            Console.WriteLine("Sales Total: " + salesTotal);
            Console.WriteLine("Sales Percent: " + salesPercent);
            Console.WriteLine("Sales Amount: " + salesAmount);

        }
    }
}
